### ISSUE TITLE
Examples code still using the older version of resource names

### ISSUE THREAD

**Issue by rsilverst** [Larpon/RangeSeekBarExamples#2]
After creating examples project in Android Studio and cloning RangeSeekBar as a lib, the project will not build because your resource naming in latest of the library has changed from what the examples are calling.

**Comment by larpon** [comment]
Ouch - I'll better fix that

**Comment by larpon** [comment]
Should be fixed in 9a291de4a

**Comment by rsilverst** [comment]
thank you! i had just got done manually tweaking it in my local code when i saw your fix :)

**Comment by larpon** [comment]
:+1:
